### PR TITLE
[F2F-329] CMA -> ID selection same ID -> CMA

### PR DESCRIPTION
**Pull request by GDainton**
### Issue tracking

- [F2F-329](https://govukverify.atlassian.net/browse/F2F-329)

### Environment variables or secrets

- [ ] Documented in the README
- [ ] Added screenshots to show the implementation is working
- [ ] Ran cfn-lint on any SAM templates

### Other considerations

[F2F-329]: https://govukverify.atlassian.net/browse/F2F-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by vibhutikaushal — COMMENTED** [review]
Please remove the tag
Correct flow is check_answers →Expiry date-> document_selection → check_answers

**Review by vibhutikaushal — COMMENTED** [review]
Request to please update the steps as discussed

**Comment by GDainton** [comment]
Descoped

**Comment by GDainton** [comment]
Descoped

**Pull request closed without merging**
